Fix NPE by making bool parameter @required
rekab-app/background_locator pull request #179
Opened 2021-01-04 17:19 UTC by komape

This PR fixes the issue described in #175.

Alternatively the parameter could get a default value assigned but I wasn't sure if `true` or `false` is better.

2021-01-05 05:33 UTC, mehdok commented
@komape 
Thank you for your contribution;

2021-01-05 05:36 UTC, mehdok requested changes
It is better to set the default value to `false`
`@required bool autoStop = false`

2021-01-05 08:17 UTC, komape commented
@mehdok But then you get the following warning:

```
The type parameter 'autoStop' is annotated with @required but only named parameters without a default value can be annotated with it.
Remove @required.dart(invalid_required_named_param)
```

What do you prefer?

```dart
@required autoStop,
```

or

```dart
autoStop = false,
```

2021-01-05 08:18 UTC, komape commented
If the parameter is marked as `@required`, everyone who updates their `background_locator` will receive a warning if they don't set this parameter. In my opinion, this is enough.

2021-01-06 05:47 UTC, mehdok commented
You are right, but this parameter is really an optional one, it should be false unless the user wants it to be true. so I think it's better to remove the `@required` and just provide a default value for it:
````dart
bool autoStop = false
````

2021-01-06 11:17 UTC, komape commented
Done.

2021-01-07 06:11 UTC, merged